### ISSUE TITLE
nemrod:elastica.populate                               

### ISSUE THREAD

**Issue by NadaBen** [conjecto/nemrod#10]
Hello, 
i'm trying to user elasticsearch with nemrod as you did in your demo project, i created the index manually using console, and when i try to use nemrod:elastica:populate it gives me this error, i search in the web but i did not find anything like this error

`"C:\wamp\bin\php\php5.5.12\php.exe" "C:\wamp\www\rdfTest\app\console" "--ansi" "nemrod:elastica:populate" "--index=photoresource"
Populating photoresource

  [EasyRdf\Http\Exception]  
  HTTP request for SPARQL query failed  

Exception trace:
 () at C:\wamp\www\rdfTest\vendor\easyrdf\easyrdf\lib\Sparql\Client.php:247
 EasyRdf\Sparql\Client->request() at C:\wamp\www\rdfTest\vendor\easyrdf\easyrdf\lib\Sparql\Client.php:128
 EasyRdf\Sparql\Client->query() at C:\wamp\www\rdfTest\vendor\conjecto\nemrod\src\Conjecto\Nemrod\QueryBuilder\Query.php:252
 Conjecto\Nemrod\QueryBuilder\Query->execute() at C:\wamp\www\rdfTest\vendor\conjecto\nemrod\src\Conjecto\Nemrod\ElasticSearch\Populator.php:239
 Conjecto\Nemrod\ElasticSearch\Populator->getSize() at C:\wamp\www\rdfTest\vendor\conjecto\nemrod\src\Conjecto\Nemrod\ElasticSearch\Populator.php:116
 Conjecto\Nemrod\ElasticSearch\Populator->populateType() at C:\wamp\www\rdfTest\vendor\conjecto\nemrod\src\Conjecto\Nemrod\ElasticSearch\Populator.php:92
 Conjecto\Nemrod\ElasticSearch\Populator->populate() at C:\wamp\www\rdfTest\vendor\conjecto\nemrod\src\Conjecto\Nemrod\Bundle\ElasticaBundle\Command\PopulatorCommand.php:107
 Conjecto\Nemrod\Bundle\ElasticaBundle\Command\PopulatorCommand->execute() at C:\wamp\www\rdfTest\vendor\symfony\symfony\src\Symfony\Component\Console\Command\Command.php:259
 Symfony\Component\Console\Command\Command->run() at C:\wamp\www\rdfTest\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:860
 Symfony\Component\Console\Application->doRunCommand() at C:\wamp\www\rdfTest\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:192
 Symfony\Component\Console\Application->doRun() at C:\wamp\www\rdfTest\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Console\Application.php:92
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at C:\wamp\www\rdfTest\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:123
 Symfony\Component\Console\Application->run() at C:\wamp\www\rdfTest\app\console:27

nemrod:elastica:populate [--index [INDEX]] [--type [TYPE]] [--batch [BATCH]] [--no-reset] [--no-clear-cache] [--timeout [TIMEOUT]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command>
`

**Comment by conjectwan** [comment]
Hello,

I think there is a problem with your frame. Try with just a little frame to begin. Like
{
"@type": "yourRdfType",
"rdfs:label": {}
}.

You can also try a nemrod:elastica:reset --index=yourIndex
and a nemrod:elastica:populate --index=yourIndex --type=yourType (see laureate in demo and not terms:Laureate for example).

**Comment by NadaBen** [comment]
My frame is as follows: `{
 {
  "@type": "rdf:Description",
  "rdfs:label": {},
  "dc:description": {}, 
  "dc:rights": {},
  "dc:subject": {},
  "dc:publisher": {},
  "dc:date": {},
  "dc:title": {},
  "dc:source": {},
  "dc:language": {},
  "dc:contributor": {},
  "dc:creator": {},
  "dc:coverage": {},
  "dc:type": {}
}

and my config elastic part : 
`elastica:
   clients:
    default:
      host: %elasticsearch_host%
      port: %elasticsearch_port%

   indexes:
    photoresource:
      client: default
      settings:
        index:
          analysis:
            analyzer:
              en:
               tokenizer: standard
      types:
        photoresource:
          type: "rdf:Description"
          frame: "@RDFTestImages/PhotoResource/PhotoResource.jsonld"`

when i nemrod:elastica:populate --index=photoresource --type=rdf:Description  ; it gives me this error : Resetting photoresource/rdf:Description

  [InvalidArgumentException]  
  Type "rdf:Description" does not exist on index "photoresource"

**Comment by conjectwan** [comment]
The type option has to be photoresource and not rdf:Description.
So your command is nemrod:elastica:populate --index=photoresource --type=photoresource . I'll test your frame to see if I can find the problem.

**Comment by NadaBen** [comment]
it give me Resetting photoresource/photoresource
Done.  but how to know that data in virtuoso are indexed and populated ?

**Comment by conjectwan** [comment]
If you make a reset, datas are not indexed. You have to do the populate command. The reset remove and recreate your index.

To see datas in elasticsearch, the better is to install the [plugin head ](https://mobz.github.io/elasticsearch-head/).

**Comment by NadaBen** [comment]
when i try it with populate , it gives me  Populating photoresource

0 entries

```
0 [>---------------------------]  1 sec, Ok i'll see plugin head
```

**Comment by conjectwan** [comment]
If there are 0 entries, no resources were found.

**Comment by NadaBen** [comment]
so normally it's coect directly with the sparql endpoint , how it works for populate data ??

**Comment by conjectwan** [comment]
Yes ES create queries from frames to request directly the sparql endpoint. Datas are serialized and posted to ES.

You can make a request in your endpoint to verify if resources exist:

SELECT (COUNT( DISTINCT ?s) as ?total) WHERE { ?s a rdf:Description}

**Comment by conjectwan** [comment]
Try to complete your frame with
**"@omitDefault": true**,

**Comment by NadaBen** [comment]
when i try the request SELECT (COUNT( DISTINCT ?s) as ?total) WHERE { ?s a rdf:Description}  it gives me total=0

**Comment by conjectwan** [comment]
It can't index resources if there are not exist :)
I advise you to use omitDefault to index datas in ES. With it, predicate values become optional, which is not the case without it.

**Comment by NadaBen** [comment]
```
    $all = $repository->getQueryBuilder()
        ->select("?s")
        ->where('?s dc:language'. '\''.$p.'\'')
        ->getQuery()
        ->execute();
```

when i try to excute this request it gives me results , so where is the problem with my resources here ?

**Comment by conjectwan** [comment]
rdf:Description is not a resource rdf type, so you can't index them like this. You need to index resources with a correct rdf:type.

You can make this SPARQL request to see all your resource types
SELECT DISTINCT ?type WHERE { ?s rdf:type ?type }

**Comment by NadaBen** [comment]
no exesting type, in result

**Comment by NadaBen** [comment]
this is a part of my rdf data   <rdf:RDF
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    xmlns:dc="http://purl.org/dc/elements/1.1/" > 
  <rdf:Description rdf:about="http://localhost/testp/resource/image/rr">
    dc:descriptionrrrrrrrrrrrr/dc:description
    dc:rightsrarararararara/dc:rights
    dc:subjectrrrrrr/dc:subject
    dc:publisherroro/dc:publisher
    dc:dateThu Mar 03 14:16:15 CET 2016/dc:date
    <dc:title xml:lang="fr">rr/dc:title
    dc:sourcehttp:rr.com/dc:source
    dc:languagefr/dc:language
    dc:contributoramn/dc:contributor
    dc:creatorrriiri/dc:creator
    dc:coveragewww/dc:coverage
    dc:typepng/dc:type
  /rdf:Description

**Comment by conjectwan** [comment]
So it can't work :) 

Test 

Insert this in your triplestore :
prefix rdfs: http://www.w3.org/2000/01/rdf-schema#
prefix rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
prefix dc: http://purl.org/dc/elements/1.1/

INSERT DATA {
  http://www.w3.org/1999/02/22-rdf-syntax-ns#Resource/1  rdf:type rdfs:Resource . 
  http://www.w3.org/1999/02/22-rdf-syntax-ns#Resource/1  rdfs:label "My resource" . 
  http://www.w3.org/1999/02/22-rdf-syntax-ns#Resource/1  dc:language "en" .  
}

In config.yml : 
types:
rdfresource:
type: "rdfs:Resource"
frame: "@RDFTestImages/RdfResource.jsonld"

In your frame : 

{
"@type": "rdf:Resource",
"@omitDefault": true,
"rdfs:label": {},
"dc:language": {}
}

The @type in your frame corresponds with the rdf:type, which in absolutely needed.

**Comment by conjectwan** [comment]
And you can specify your dc:language to {"en"} for example to have only resources with english language.

**Comment by NadaBen** [comment]
so i must change all rdf syntax ?
`<rdf:RDF
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    xmlns:dc="http://purl.org/dc/elements/1.1/" > 
  <rdf:Description rdf:about="http://localhost/testp/resource/image/rr">
    <dc:description>rrrrrrrrrrrr</dc:description>
    <dc:rights>rarararararara</dc:rights>
    <dc:subject>rrrrrr</dc:subject>
    <dc:publisher>roro</dc:publisher>
    <dc:date>Thu Mar 03 14:16:15 CET 2016</dc:date>
    <dc:title xml:lang="fr">rr</dc:title>
    <dc:source>http:rr.com</dc:source>
    <dc:language>fr</dc:language>
    <dc:contributor>amn</dc:contributor>
    <dc:creator>rriiri</dc:creator>
    <dc:coverage>www</dc:coverage>
    <dc:type>png</dc:type>
  </rdf:Description>`

**Comment by conjectwan** [comment]
You need to add a rdf:type to your resources to create rdf objects. The rest can be kept.
Your rdf:type can be arbitrary like a rdf:Photo for example.

**Comment by NadaBen** [comment]
Okey i'll try that, thank you for your help,

**Comment by NadaBen** [comment]
`"C:\wamp\bin\php\php5.5.12\php.exe" "C:\wamp\www\rdfTest\app\console" "--ansi" "nemrod:elastica:populate" "--index=photoresource" "--type=photoresource"
Populating photoresource

2 entries

 0/1 [>---------------------------]   0%  1 sec

  [EasyRdf\Http\Exception]  
  HTTP request for SPARQL query failed  

Exception trace:
 () at C:\wamp\www\rdfTest\vendor\easyrdf\easyrdf\lib\Sparql\Client.php:247
 EasyRdf\Sparql\Client->request() at C:\wamp\www\rdfTest\vendor\easyrdf\easyrdf\lib\Sparql\Client.php:128
 EasyRdf\Sparql\Client->query() at C:\wamp\www\rdfTest\vendor\conjecto\nemrod\src\Conjecto\Nemrod\QueryBuilder\Query.php:252
 Conjecto\Nemrod\QueryBuilder\Query->execute() at C:\wamp\www\rdfTest\vendor\conjecto\nemrod\src\Conjecto\Nemrod\Framing\Provider\ConstructedGraphProvider.php:44
 Conjecto\Nemrod\Framing\Provider\ConstructedGraphProvider->getGraph() at C:\wamp\www\rdfTest\vendor\conjecto\nemrod\src\Conjecto\Nemrod\Framing\Serializer\JsonLdSerializer.php:128
 Conjecto\Nemrod\Framing\Serializer\JsonLdSerializer->serialize() at C:\wamp\www\rdfTest\vendor\conjecto\nemrod\src\Conjecto\Nemrod\ElasticSearch\ResourceToDocumentTransformer.php:76
 Conjecto\Nemrod\ElasticSearch\ResourceToDocumentTransformer->transform() at C:\wamp\www\rdfTest\vendor\conjecto\nemrod\src\Conjecto\Nemrod\ElasticSearch\Populator.php:135
 Conjecto\Nemrod\ElasticSearch\Populator->populateType() at C:\wamp\www\rdfTest\vendor\conjecto\nemrod\src\Conjecto\Nemrod\ElasticSearch\Populator.php:92
 Conjecto\Nemrod\ElasticSearch\Populator->populate() at C:\wamp\www\rdfTest\vendor\conjecto\nemrod\src\Conjecto\Nemrod\Bundle\ElasticaBundle\Command\PopulatorCommand.php:107
 Conjecto\Nemrod\Bundle\ElasticaBundle\Command\PopulatorCommand->execute() at C:\wamp\www\rdfTest\vendor\symfony\symfony\src\Symfony\Component\Console\Command\Command.php:259
 Symfony\Component\Console\Command\Command->run() at C:\wamp\www\rdfTest\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:860
 Symfony\Component\Console\Application->doRunCommand() at C:\wamp\www\rdfTest\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:192
 Symfony\Component\Console\Application->doRun() at C:\wamp\www\rdfTest\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Console\Application.php:92
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at C:\wamp\www\rdfTest\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:123
 Symfony\Component\Console\Application->run() at C:\wamp\www\rdfTest\app\console:27

nemrod:elastica:populate [--index [INDEX]] [--type [TYPE]] [--batch [BATCH]] [--no-reset] [--no-clear-cache] [--timeout [TIMEOUT]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command>`

frame file : 
`{
  "@type": "rdf:type",
  "@omitDefault": true,
  "rdfs:label": {},
  "dc:description": {}, 
  "dc:rights": {},
  "dc:subject": {},
  "dc:publisher": {},
  "dc:date": {},
  "dc:title": {},
  "dc:source": {},
  "dc:language": {},
  "dc:contributor": {},
  "dc:creator": {},
  "dc:coverage": {},
  "dc:type": {}
}
`

config file : 
`elastica:
   clients:
    default:
      host: %elasticsearch_host%
      port: %elasticsearch_port%

   indexes:
    photoresource:
      client: default
      settings:
        index:
          analysis:
            analyzer:
              en:
               tokenizer: standard
      types:
        photoresource:
          type: "rdf:type"
          frame: "@RDFTestImages/PhotoResource/PhotoResource.jsonld"`

rdf resource:

`/**
- Class PhotoResource
- @package TestTask\PhotosBundle\RdfResource
- @Resource(types={"rdf:type"}, uriPattern ="")
- @Serializer\JsonLd(frame="@TestTaskImages/PhotoResource/PhotoResource.jsonld")
  */
  class PhotoResource extends BaseResource
  {
  }`

rdf data syntax : 
`<rdf:RDF
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    xmlns:dc="http://purl.org/dc/elements/1.1/" > 
  <rdf:type rdf:Description="http://localhost/testp/resource/image/rr">
    <dc:description>rrrrrrrrrrrr</dc:description>
    <dc:rights>rarararararara</dc:rights>
    <dc:subject>rrrrrr</dc:subject>
    <dc:publisher>roro</dc:publisher>
    <dc:date>Thu Mar 03 14:16:15 CET 2016</dc:date>
    <dc:title xml:lang="fr">rr</dc:title>
    <dc:source>http:rr.com</dc:source>
    <dc:language>fr</dc:language>
    <dc:contributor>amn</dc:contributor>
    <dc:creator>rriiri</dc:creator>
    <dc:coverage>www</dc:coverage>
    <dc:type>png</dc:type>
  </rdf:type>`

**Comment by conjectwan** [comment]
The @type correspond to the rdf:type so we have to specify the rdf:type with @type. The sparql request from your frame is CONSTRUCT{  [...] } WHERE { ?s rdf:type rdf:type. [...] }. It would be @type: rdf:myPhoto for example.

**Comment by conjectwan** [comment]
Can I close the issue ?

**Comment by NadaBen** [comment]
yes thank you
