### ISSUE TITLE
Compile Error: Declaration of Conjecto\Nemrod\Bundle\NemrodBundle\ParamConverter\ResourceParamConverter::apply() must be compatible

### ISSUE THREAD

**Issue by NadaBen** [conjecto/nemrod#11]
Hello,
when i updated my composer to add a new bundle, nemrod bundle change version and it gives me this error, how to solve that please? 
`FatalErrorException in ResourceParamConverter.php line 27:
Compile Error: Declaration of Conjecto\Nemrod\Bundle\NemrodBundle\ParamConverter\ResourceParamConverter::apply() must be compatible with Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\ParamConverterInterface::apply(Symfony\Component\HttpFoundation\Request $request, Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter $configuration)`

**Comment by conjectwan** [comment]
Hello, I accepted a pull-request that is incomplete and I undo the modification. So you can re-pull it would work again :)

**Comment by NadaBen** [comment]
How i can i re-pull it ??

**Comment by conjectwan** [comment]
composer update conjecto/nemrod

**Comment by NadaBen** [comment]
I did it but same error

**Comment by conjectwan** [comment]
In your composer.json, which is the Nemrod version  ?

**Comment by NadaBen** [comment]
```
    "conjecto/nemrod": "@dev",
    "easyrdf/easyrdf": "@dev",
    "conjecto/json-ld": "@dev",
```

**Comment by conjectwan** [comment]
Use "conjecto/nemrod": "dev-master" and make a composer update conjecto/nemrod. It would have work previously but sometimes it take times to reports dependency updates with composer.

**Comment by NadaBen** [comment]
it works, thank you
