### ISSUE TITLE
decouple

### ISSUE THREAD

**Issue by lsmith77** [conjecto/nemrod#3]
interesting project. seems like it would be a good idea to decouple things a bit. like separating  the SPARQL query builder, maybe also the JMS serializer visitors etc.

BTW have a look at https://github.com/flack/createphp and https://github.com/symfony-cmf/CreateBundle

**Comment by bdecarne** [comment]
Hi ! Thanx for your message. You are absolutely right about decoupling some parts, Nemrod could even be independent from Symfony.
