### ISSUE TITLE
conjecto/nemrod 0.1.0 requires easyrdf/easyrdf dev-master -> no matching package found.

### ISSUE THREAD

**Issue by StephanePate** [conjecto/nemrod#6]
How can I solve this issue ?

**Comment by conjectwan** [comment]
Hey,

Tanks for alert us. We updated the master branch and its documentation.

The fastest way to test nemrod is to clone the nemrod-demo at https://github.com/conjecto/nemrod-demo and to follow the documentation.

If you want to install nemrod from an empty symfony project, you need to know that nemrod has only be tested with symfony 2.6. You can create a symfony 2.6 project with this command line :
- composer create-project symfony/framework-standard-edition my_project_name "2.6.*"

Do not hesitate to question us if you have any problem.

Good tests !
