### ISSUE TITLE
Notice: Undefined index: indexes

### ISSUE THREAD

**Issue by NadaBen** [conjecto/nemrod#8]
Hello, please i need some help, when i update my composer and i try to clear the catch it gives me this error : 
1/ ContextErrorException in ElasticaFramingRegistrationPass.php line 28:
Notice: Undefined index: indexes,  

2/at ErrorHandler->handleError('8', 'Undefined index: indexes', 'C:\wamp\www\test\vendor\conjecto\nemrod\src\Conjecto\Nemrod\Bundle\ElasticaBundle\DependencyInjection\CompilerPass\ElasticaFramingRegistrationPass.php', '28', array('container' => object(ContainerBuilder), 'config' => array(), 'jsonLdFrameLoader' => object(JsonLdFrameLoader))) in ElasticaFramingRegistrationPass.php line 28

line 28 of ElasticaFramingRegistrationPass.php is as follows:
`foreach ($config['indexes'] as $name => $types) {`

how to solve that please ?

**Comment by conjectwan** [comment]
Hello,

Have you create an elastica block in your config.yml ? You have an example in our demo project
 [demo project](https://github.com/conjecto/nemrod-demo/blob/master/app/config/config.yml). The error is surely caught when the composer rebuild the application cache. And Nemrod read the config.yml file during the cache compilation.

If you does not want to work with elasticsearch, you can also remove the ElasticaBundle from the AppKernel.

I hope it will solve your problem. If not, do not hesitate to ask us some help again ;-)

**Comment by NadaBen** [comment]
solved when i removed elasticsearch,, but if i use elasticsearch with the demo project it gives me this error
`Twig_Error_Loader in unable to find frame`  have you any idea about that ?

**Comment by conjectwan** [comment]
Nemrod use JsonLD frames to serialize RDF resources. So, it is used for elasticsearch serialization. 

If we read the config.yml file in the demo project, we can see a _frame: "@Demo/Laureate/laureate.jsonld"_

A such path will search a frame in _DemoBundle/Resources/frames/Laureate/laureate.jsonld_. Maybe this frame does not exist in your project ?

**Comment by NadaBen** [comment]
i did that , same error

**Comment by conjectwan** [comment]
Did you try a cache:clear ?

**Comment by NadaBen** [comment]
when i clear my cache it gives me 
`[Twig_Error_Loader]                                                 
  Unable to find frame "@Photos/PhotoResource/PhotoResource.jsonld".`

**Comment by NadaBen** [comment]
this is my class resource 
`<?php

namespace TestTask\PhotosBundle\RdfResource;

use Conjecto\Nemrod\Resource as BaseResource;
use Conjecto\Nemrod\ResourceManager\Annotation\Resource;
use Conjecto\Nemrod\ResourceManager\Annotation\Property;
use Conjecto\Nemrod\Framing\Annotation as Serializer;

/**
- Class PhotoResource
- @package TestTask\PhotosBundle\RdfResource
- @Resource(types={"terms:PhotoResource "}, uriPattern = "")
- @Serializer\JsonLd(frame="@Photos/PhotoResource/PhotoResource.jsonld")
  */
  class PhotoResource extends BaseResource
  {
  }
  `

the file PhotoResource.jsonld is in TestTask\PhotosBundle\Resources\PhotoResource

and my configuration is as follows : 
`elastica:
   clients:
    default:
      host: %elasticsearch_host%
      port: %elasticsearch_port%

   indexes:
    PhotoResource:
      client: default
      settings:
        index:
          analysis:
            analyzer:
              en:
               tokenizer: standard
      types:
        PhotoResource:
          type: "terms:PhotoResource"
          frame: "@Photos/PhotoResource/PhotoResource.jsonld"`

**Comment by conjectwan** [comment]
If you remove the line _@Serializer\JsonLd(frame="@Photos/PhotoResource/PhotoResource.jsonld")_, does the problem persist ?

**Comment by NadaBen** [comment]
yes the same error

**Comment by NadaBen** [comment]
is he has a relationship with the twig files ??

**Comment by conjectwan** [comment]
No but we use the twig file finder to get frame files

**Comment by NadaBen** [comment]
yes so do you have any other idea ?

**Comment by conjectwan** [comment]
Yes there is a problem with the frame path. I'm searching the corresponding code in Nemrod to guide you find the searched path.

**Comment by NadaBen** [comment]
Ok i'm waiting for your response, thank you

**Comment by conjectwan** [comment]
You can go to Twig_Loader_Filesystem file at line 200 and dump all _$path.'/'.$shortname_ searched. You should see you JsonLD frame with expanded searched path.

**Comment by NadaBen** [comment]
in this code 
`  foreach ($this->paths[$namespace] as $path) {
            if (is_file($path.'/'.$shortname)) {
                if (false !== $realpath = realpath($path.'/'.$shortname)) {
                    return $this->cache[$name] = $realpath;
                }

```
            return $this->cache[$name] = $path.'/'.$shortname;
        }
    }`
```

i must do what, i dont understand

**Comment by conjectwan** [comment]
add var_dump($path.'/'.$shortname); before if (is_file...) to see all searched pathes. You should see your jsonld frame pathes

**Comment by conjectwan** [comment]
and verify if there are correct

**Comment by NadaBen** [comment]
i did that 
`        foreach ($this->paths[$namespace] as $path) {
            var_dump($path.'/'.$shortname);
            if (is_file($path.'/'.$shortname)) {
                if (false !== $realpath = realpath($path.'/'.$shortname)) {
                    return $this->cache[$name] = $realpath;
                }

```
            return $this->cache[$name] = $path.'/'.$shortname;
        }
    }`
```

and i clear cache but still the same error

**Comment by conjectwan** [comment]
Yes but it should display your entire jsonld file path. Is it displayed and is it correct ?

**Comment by NadaBen** [comment]
ah it's not displayed

**Comment by conjectwan** [comment]
Go to Conjecto\Nemrod\Framing\Loader\JsonLdFrameLoader at line 130 in getSource function add a var_dump($name); before return line to see if it enters in function

**Comment by NadaBen** [comment]
in JsonLdFrameLoader , i dont have getSource , i have it in function getFrame in line 56 as follows:

`   /**
     \* Return the decoded frame.
     */
    public function getFrame($name, $assoc = true)
    {
        $decoded = json_decode($this->getSource($name), $assoc);
        if ($decoded === null) {
            throw new \Twig_Error_Loader(sprintf('Unable to decode frame "%s".', $name));
        }

```
    return $decoded;
}`
```

**Comment by conjectwan** [comment]
My fault, this function is in FileSystem class. If you do the var_dump at line 56 before the getSource, does it display something during cache:clear ?

**Comment by NadaBen** [comment]
yes it shows me that:
string(42) "@Photos/PhotoResource/PhotoResource.jsonld"

and the same error

**Comment by conjectwan** [comment]
So it should enter in FileSystem::findTemplate method. Can you display several var_dump to identify when the function is returned

**Comment by NadaBen** [comment]
when i display var_dump in FileSystem::findTemplate method. it gives me string(42) "@Photos/PhotoResource/PhotoResource.jsonld" too

**Comment by conjectwan** [comment]
Yes but can you make a var_dump before all returns to see which return is called

**Comment by NadaBen** [comment]
this one before return $this->cache[$name] = $path.'/'.$shortname; which is returned

**Comment by erwanastro** [comment]
with  them name corresponding to your frame ?

**Comment by conjectwan** [comment]
And what is displayed if you do a var_dump($path.'/'.$shortname) just before this return ?

**Comment by NadaBen** [comment]
i'm sorry it was a mistake, it is not displayed with any returned in FileSystem::findTemplate method

**Comment by conjectwan** [comment]
Ok... can you follow the Conjecto\Nemrod\Framing\Loader\JsonLdFrameLoader::getFrame process and with var_dump see where it goes ? I have no other ideas

**Comment by NadaBen** [comment]
null, when i try to display that too $decoded = json_decode($this->getSource($name), $assoc);
it gives me null

**Comment by NadaBen** [comment]
because getSource gives null , so problem is in findTemplate method

**Comment by conjectwan** [comment]
in findTemplate methods, where is it return ?
Have you register your new bundle in the AppKernel ?

**Comment by NadaBen** [comment]
yes all bundles are registred  
           new Conjecto\Nemrod\Bundle\NemrodBundle\NemrodBundle(),
            new Conjecto\Nemrod\Bundle\ElasticaBundle\ElasticaBundle(),
            new TestTask\PhotosBundle\TestTaskPhotosBundle(),

it is not displayed with any returned in FileSystem::findTemplate method

**Comment by NadaBen** [comment]
if i use nemrod witout elastica, can i display, use sparql and create rdf resources and entities, because i want to connect the application with virtuoso ?

**Comment by conjectwan** [comment]
Try to replace "Photos" in your frame path by "TestTaskPhotos".

Yes you can create, edit and delete RDF resources, especially with forms.

**Comment by NadaBen** [comment]
when i try it with TestTaskPhotos, it shows me this error 
 [Twig_Error_Loader]  
  Unable to decode frame "@TestTaskPhotos/PhotoResource/PhotoResource.jsonld"  
  .

**Comment by conjectwan** [comment]
Can you go in vendor/twig/twig/CHANGELOG and see which version it is at top of the file please ?

**Comment by NadaBen** [comment]
- 1.24.0 (2016-01-25) version

**Comment by conjectwan** [comment]
ok I have the same version.

Can you go on addPath method in filesystem class and add var_dump($path); var_dump($namespace); and see if it display something

**Comment by NadaBen** [comment]
It gives me 
string(59) "C:\wamp\www\test\src\TestTask\PhotosBundle/Resources/frames"
string(14) "TestTaskPhotos"

and the error
 [Twig_Error_Loader]  
  Unable to decode frame "@TestTaskPhotos/PhotoResource/PhotoResource.jsonld"  
  .

**Comment by conjectwan** [comment]
Ok so you have to use a @TestTaskPhotos / instead of @ Photos with your frame.

You should have your file at path _C:\wamp\www\test\src\TestTask\PhotosBundle\Resources\frames\PhotoResource\PhotoResource.jsonld_ . Is it the case ? Just to be sure.

**Comment by NadaBen** [comment]
exactly i must to have this path, i'm using @TestTaskPhotos

**Comment by conjectwan** [comment]
Can you send me your zipped bundle at my email address please ?

**Comment by NadaBen** [comment]
Done

**Comment by conjectwan** [comment]
You have to remove the last coma of your frame after dc:type: {}

**Comment by conjectwan** [comment]
Does it work ? Your frame was not correct

**Comment by NadaBen** [comment]
it works now. thank youu a lot
