### ISSUE TITLE
Nemrod and Virtuoso

### ISSUE THREAD

**Issue by NadaBen** [conjecto/nemrod#9]
Hello
do you have an idea how to use virtuoso with Nemrod instead of blazegraph to produce and consume RDF resources ?

I did that in parameters file:
  `nemrod_endpoint_host: 'http://localhost'
    nemrod_endpoint_port: 8890
    nemrod_endpoint_path: sparql?default-graph-uri=http://localhost:8890/bigdata`

but it gives me this error: HTTP request for SPARQL query failed

`Client ->update ('INSERT { <http://data.nobelprize.org/resource/laureateaward/571c883784784> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://data.nobelprize.org/terms/LaureateAward> . <http://data.nobelprize.org/resource/laureateaward/571c883784784> <http://data.nobelprize.org/terms/year> "2015"^^<http://www.w3.org/2001/XMLSchema#integer> . <http://data.nobelprize.org/resource/laureateaward/571c883784784> <http://data.nobelprize.org/terms/category> <http://data.nobelprize.org/resource/category/Chemistry> . <http://data.nobelprize.org/resource/laureateaward/571c883784784> <http://data.nobelprize.org/terms/field> "field" . <http://data.nobelprize.org/resource/laureateaward/571c883784784> <http://data.nobelprize.org/terms/motivation> "motiv" . <http://data.nobelprize.org/resource/laureateaward/571c883784784> <http://data.nobelprize.org/terms/laureate> <http://data.nobelprize.org/resource/laureate/571c88378479e> . <http://data.nobelprize.org/resource/laureateaward/571c883784784> <http://www.w3.org/2000/01/rdf-schema#label> "Chemistry 2015, name family n" . <http://data.nobelprize.org/resource/laureate/571c88378479e> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://data.nobelprize.org/terms/Laureate> . <http://data.nobelprize.org/resource/laureate/571c88378479e> <http://xmlns.com/foaf/0.1/givenName> "name" . <http://data.nobelprize.org/resource/laureate/571c88378479e> <http://xmlns.com/foaf/0.1/gender> "female" . <http://data.nobelprize.org/resource/laureate/571c88378479e> <http://xmlns.com/foaf/0.1/familyName> "family n" . <http://data.nobelprize.org/resource/laureate/571c88378479e> <http://xmlns.com/foaf/0.1/birthday> "1961-01-01"^^<http://www.w3.org/2001/XMLSchema#date> . <http://data.nobelprize.org/resource/laureate/571c88378479e> <http://dbpedia.org/property/dateOfDeath> "2015-12-17"^^<http://www.w3.org/2001/XMLSchema#date> . <http://data.nobelprize.org/resource/laureate/571c88378479e> <http://www.w3.org/2000/01/rdf-schema#label> "name family n" } WHERE {} ') 
in C:\wamp\www\nemrod\vendor\conjecto\nemrod\src\Conjecto\Nemrod\QueryBuilder\Query.php at line 295`

and others errors

**Comment by conjectwan** [comment]
Hey, I didn't survey Github and I didn't see your issue. Can I know what was your error ?

**Comment by NadaBen** [comment]
it's solved, thank you, can i ask an other question, when i try to execute this query        $all = ```
`$repository->getQueryBuilder()
            ->insert(" http://localhost/testp/resource/image/$id 
                         dc:description . '\''.$description.'\'' ;
                         dc:rights . '\''.$rights.'\'' ;
                         dc:subject . '\''.$subject.'\'';
                         dc:publisher . '\''.$publisher.'\'';
                         dc:date . '\''.$date.'\'';
                         dc:title . '\''.$title.'\'';
                         dc:source . '\''.$source.'\'';
                         dc:language . '\''.$language.'\'';
                         dc:contributor . '\''.$contributor.'\'';
                         dc:creator . '\''.$creator.'\'';
                         dc:coverage . '\''.$coverage.'\'';
                         dc:type . '\''.$type.'\''".)`

it gives me this error    "code": 500,
  "message": "HTTP request for SPARQL query failed"

**Comment by conjectwan** [comment]
Before your $qb->update(), you can make a echo $qb->getSparqlQuery() and execute the result on your sparql interface to see more details.

**Comment by NadaBen** [comment]
i tried  echo $qb->getSparqlQuery() but it gives me undefined method  getSparqlQuery(), i want to know if you are defining the insert query like i did or not since in your documentation there is no example for insert queries

**Comment by conjectwan** [comment]
Make $qb=$repository->getQueryBuilder();
echo $qb->insert(...)->getSparqlQuery();

Yes it seems correct but your  http://localhost/testp/resource/image/$id is weird.

But on are your sure your update endpoint address is correct in Nemrod ?

**Comment by conjectwan** [comment]
In fact you must not make $repo->getQueryBuilder() because its initializing a query construct . If you do this make a $qb->reset() or make a $rm->getQueryBuilder() to have an empty query builder.

**Comment by NadaBen** [comment]
my endpoint is correct since i try other select queries and it works, when i make $qb=$repository->getQueryBuilder();
echo $qb->insert(...)->getSparqlQuery(); it gives me

`INSERT { <http://localhost/testp/resource/image/amn> 
                         dc:description . '\''.amn.'\'' ;
                         dc:rights . '\''.amn.'\'' ;
                         dc:subject . '\''.amn.'\'';
                         dc:publisher . '\''.amn.'\'';
                         dc:date . '\''.amn.'\'';
                         dc:title . '\''.amn.'\'';
                         dc:source . '\''.amn.'\'';
                         dc:language . '\''.amn.'\'';
                         dc:contributor . '\''.amnamn.'\'';
                         dc:creator . '\''.amn.'\'';
                         dc:coverage . '\''.amn.'\'';
                         dc:type . '\''.amn.'\''. } WHERE { ?s a rdf:Description. ?s ?p ?o } {"code":500,"message":"HTTP request for SPARQL query failed"}`

**Comment by conjectwan** [comment]
Your string is not correct. Try something like that 
$qb->insert("http://localhost/testp/resource/image/$id dc:description \"$description\"; ...");

**Comment by NadaBen** [comment]
it doesn't work either, when i try the same query in the endpoint directly and it works   like this  INSERT DATA
{ 
  http://localhost/testp/resource/image/nada 
                         dc:description "nada.descrip" ;
                         dc:rights "nada.rights" ;
                         dc:subject "nada.subject";
                         dc:publisher "nada.publisher";
                         dc:date "Thu Mar 03 14:16:15 CET 2016";
                         dc:title "nada.title";
                         dc:source "nada.source";
                         dc:language "fr";
                         dc:contributor "nada.contributor";
                         dc:creator "nada.creator";
                         dc:coverage "www";
                         dc:type "png".

}

**Comment by conjectwan** [comment]
You should not have the "WHERE { ?s a rdf:Description. ?s ?p ?o } " in your query.

**Comment by NadaBen** [comment]
yes that why i'm asking you how you are defining the insert query because when i use select query like         $all = $repository->getQueryBuilder()
            ->select("?s")
            ->where('?s dc:language'. '\''.$p.'\'')
            ->getQuery()
            ->execute();  it works .. for insert i dont know how you are defining the query

**Comment by conjectwan** [comment]
If you pass by the repository to get the query builder, this query builder is already initialized with a construct query to get all objects with passed rdf:type.
The repository do : 
$qb->construct("?s ?p ?o")->where("?s a rdf:type")->andWhere("?s ?p ?o"); Yhe query builder is then returned to you.

So if you do a select with this query builder, you will keep the ->where("?s a rdf:type")->andWhere("?s ?p ?o") parts and the construct will be overridden by your select. It is exactly the same think if you do an insert or a delete.

So the result is that you have a $qb->insert(datas)->where("?s a rdf:type")->andWhere("?s ?p ?o"); But in this case the where is not correct because it has to be empty.

You have three solutions to correct your problem.
- You can ask an empty query builder (with no where part). To do this, make a $this->get('rm')->-getQueryBuilder() and you will be able to do your inserts.
- You can call this repository query builder and reset it, it is exactly the same that the first solution.
- You can make your insert like before and override the where part with an empty where call like $qb->where();

**Comment by NadaBen** [comment]
when i try your 3th solution it gives me Warning: Missing argument 1 for Conjecto\Nemrod\QueryBuilder::where(), called in Class X

**Comment by conjectwan** [comment]
a $qb->where("") should be better :)

**Comment by NadaBen** [comment]
an other error "code": 500,
  "message": "You must specify with which property you want to filter"

**Comment by conjectwan** [comment]
It seems that virtuoso in more restrective that BlazeGraph. try to add a where("?s a rdf:yourResourceType");

**Comment by NadaBen** [comment]
WHERE { ?s rdf:Description } {"code":500,"message":"HTTP request for SPARQL query failed"} :/

**Comment by conjectwan** [comment]
WHERE { ?s **a** rdf:Description }

**Comment by NadaBen** [comment]
either  WHERE { ?s rdf:Description } {"code":500,"message":"HTTP request for SPARQL query failed"}

**Comment by conjectwan** [comment]
you do not specify the rdf:type
You should do a WHERE { ?s **rdf:type** rdf:Description } or a WHERE { ?s **a** rdf:Description }

**Comment by NadaBen** [comment]
WHERE { ?s *a rdf:Description } {"code":500,"message":"HTTP request for SPARQL query failed"}

 WHERE { ?s rdf:type *rdf:Description } {"code":500,"message":"HTTP request for SPARQL query failed"}

**Comment by conjectwan** [comment]
Can you give me your entire request please ? I'm lost :)

**Comment by NadaBen** [comment]
this is my function :
  `    /**
     \* 
     \* @ApiDoc(description="Add a photo.")
     \* @Rest\RequestParam(name="id", nullable=true, description="Tags that associates photo.")
     \* @Rest\RequestParam(name="description", nullable=true, description="Tags that associates photo.")
     \* @Rest\RequestParam(name="rights", nullable=true, description="Tags that associates photo.")
     \* @Rest\RequestParam(name="subject", nullable=true, description="Tags that associates photo.")
     \* @Rest\RequestParam(name="publisher", nullable=true, description="Tags that associates photo.")
     \* @Rest\RequestParam(name="date", nullable=true, description="Tags that associates photo.")
     \* @Rest\RequestParam(name="title", nullable=true, description="Tags that associates photo.")
     \* @Rest\RequestParam(name="source", nullable=true, description="Tags that associates photo.")
     \* @Rest\RequestParam(name="language", nullable=true, description="Tags that associates photo.")
     \* @Rest\RequestParam(name="contributor", nullable=true, description="Tags that associates photo.")
     \* @Rest\RequestParam(name="creator", nullable=true, description="Tags that associates photo.")
     \* @Rest\RequestParam(name="coverage", nullable=true, description="Tags that associates photo.")
     \* @Rest\RequestParam(name="type", nullable=true, description="Tags that associates photo.")
     \* @Rest\View()
     */
    public function postResourceAction(ParamFetcher $paramFetcher)
    {

```
            //getting manager
    $manager = $this->container->get('rm');

    //getting repository
    $repository = $manager->getRepository('rdf:Description');

    $id = $paramFetcher->get('id');
    $description = $paramFetcher->get('description');
    $rights = $paramFetcher->get('rights');
    $subject = $paramFetcher->get('subject');
    $publisher = $paramFetcher->get('publisher');
    $date = $paramFetcher->get('date');
    $title = $paramFetcher->get('title');
    $source = $paramFetcher->get('source');
    $language = $paramFetcher->get('language');
    $contributor = $paramFetcher->get('contributor');
    $creator = $paramFetcher->get('creator');
    $coverage = $paramFetcher->get('coverage');
    $type = $paramFetcher->get('type');


    //getting years by querying directly the triplet store
  $all = $repository->getQueryBuilder()
        ->insert("http://localhost/testp/resource/image/.$id.
                     dc:description . '\''.$description.'\'' ;
                     dc:rights . '\''.$rights.'\'' ;
                     dc:subject . '\''.$subject.'\'';
                     dc:publisher . '\''.$publisher.'\'';
                     dc:date . '\''.$date.'\'';
                     dc:title . '\''.$title.'\'';
                     dc:source . '\''.$source.'\'';
                     dc:language . '\''.$language.'\'';
                     dc:contributor . '\''.$contributor.'\'';
                     dc:creator . '\''.$creator.'\'';
                     dc:coverage . '\''.$coverage.'\'';
                     dc:type . '\''.$type.'\''.")
        ->where("?s rdf:type *rdf:Description")
        ->getQuery()
        ->execute();

    //getting all categories
    //$categories = $manager->getRepository('terms:Category')->findAll();

    return array("all" => $all);


}`
```

**Comment by conjectwan** [comment]
You can try two solutions : 

```
public function postResourceAction(ParamFetcher $paramFetcher)
{
    //getting manager
    $manager = $this->container->get('rm');

    // getting empty query builder
    $insertQueryBuilder = $manager->getQueryBuilder();

    //getting repository
    $repository = $manager->getRepository('rdf:Description');

    $id = $paramFetcher->get('id');
    $description = $paramFetcher->get('description');
    $rights = $paramFetcher->get('rights');
    $subject = $paramFetcher->get('subject');
    $publisher = $paramFetcher->get('publisher');
    $date = $paramFetcher->get('date');
    $title = $paramFetcher->get('title');
    $source = $paramFetcher->get('source');
    $language = $paramFetcher->get('language');
    $contributor = $paramFetcher->get('contributor');
    $creator = $paramFetcher->get('creator');
    $coverage = $paramFetcher->get('coverage');
    $type = $paramFetcher->get('type');

    // insert datas to triplestore
    $insertQueryBuilder
        ->insert("<http://localhost/testp/resource/image/$id> 
                 dc:description \"$description\" ;
                 dc:rights \"$rights\" ;
                 dc:subject \"$subject\";
                 dc:publisher \"$publisher\";
                 dc:date \"$date\";
                 dc:title \"$title\";
                 dc:source \"$source\";
                 dc:language \"$language\";
                 dc:contributor \"$contributor\";
                 dc:creator \"$creator\";
                 dc:coverage \"$coverage\";
                 dc:type \"$type\"")
        ->getQuery()
        ->update();

    //getting all categories
    //$categories = $manager->getRepository('terms:Category')->findAll();

    return array("all" => $repository->findAll());
}
```

Or another solution more integrated to Nemrod Symfony2 : 

```
public function postResourceAction(ParamFetcher $paramFetcher)
{
    $manager = $this->container->get('rm');
    $repository = $manager->getRepository('rdf:Description');

    // getting variables
    $variables = array();
    $id = $paramFetcher->get('id');
    $variables['dc:description'] = $paramFetcher->get('description');
    $variables['dc:rights'] = $paramFetcher->get('rights');
    $variables['dc:subject'] = $paramFetcher->get('subject');
    $variables['dc:publisher'] = $paramFetcher->get('publisher');
    $variables['dc:date'] = $paramFetcher->get('date');
    $variables['dc:title'] = $paramFetcher->get('title');
    $variables['dc:source'] = $paramFetcher->get('source');
    $variables['dc:language'] = $paramFetcher->get('language');
    $variables['dc:contributor'] = $paramFetcher->get('contributor');
    $variables['dc:creator'] = $paramFetcher->get('creator');
    $variables['dc:coverage'] = $paramFetcher->get('coverage');
    $variables['dc:type'] = $paramFetcher->get('type');

    $resource = $repository->find("http://localhost/testp/resource/image/$id");
    foreach ($variables as $predicate => $object) {
        $resource->add($predicate, $object);
    }
    $manager->flush();

    return array("all" => $repository->findAll());
}
```

Note that you should not add quotes like " rdf:predicate \"$object\" " if the $object is not a string.

Sorry I forgotten but you have to make a Query->update when you make a insert or a delete and not an execute.

**Comment by NadaBen** [comment]
i tried the first solution and it works with execute and not with update query .. thank you so much

**Comment by conjectwan** [comment]
Could you just try the second to see if it works with virtuoso please ?

**Comment by NadaBen** [comment]
yes with pleasure .. it gives me that  : "message": "Error: Call to a member function add() on a non-object"

**Comment by conjectwan** [comment]
Ok could you just retry with this line 
$resource = $repository->find("http://localhost/testp/resource/image/$id"); just before the foreach ?

**Comment by NadaBen** [comment]
same error, but it's the same line no ?  $resource = $repository->find("http://localhost/testp/resource/image/$id");
    foreach ($variables as $predicate => $object) {
        $resource->add($predicate, $object);
    }

**Comment by conjectwan** [comment]
Oh github has removed my chevrons... Could you try with an opening chevron before http and a closing one after $id ?

**Comment by NadaBen** [comment]
When i add the quotes , "message": "HTTP request for SPARQL query failed"

**Comment by conjectwan** [comment]
I have corrected my comment, it's chevrons that you have to add (<>)

**Comment by NadaBen** [comment]
even if i add (<>) :  "message": "HTTP request for SPARQL query failed"

**Comment by conjectwan** [comment]
Ok no problem, thanks for having tried :)

**Comment by NadaBen** [comment]
if you have other propositions, i have no problem , i can try all day

**Comment by conjectwan** [comment]
:) I close this issue.
